### ISSUE TITLE
SocketChannel.socket() is not supported for UNIX protocol

### ISSUE THREAD

**Issue by Qwertovsky** [moaxcp/x11#34]
```
Exception in thread "main" java.lang.UnsupportedOperationException: Not supported
	at java.base/sun.nio.ch.SocketChannelImpl.socket(SocketChannelImpl.java:233)
	at com.github.moaxcp.x11.x11client.X11Connection.connect(X11Connection.java:118)
	at com.github.moaxcp.x11.x11client.X11Connection.connect(X11Connection.java:145)
	at com.github.moaxcp.x11.x11client.X11Client.connect(X11Client.java:83)
```
To reproduce
```java
try(X11Client client = X11Client.connect(new DisplayName(":1"))) {
} catch (IOException e) {
}
```

**Comment by moaxcp** [comment]
Thanks! I started working on this today!

**Comment by moaxcp** [comment]
I'm switching back to junixsocket but it uses a multi-release jar which is [not supported](https://github.com/freefair/gradle-plugins/issues/824) by delombok. So I have to remove lombok from the x11-client module and release 0.18.2.

**Comment by moaxcp** [comment]
Everything should work now in 0.18.2. I was having trouble with the junixsocket modules but all of the examples work now.
